menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/haeguri
#    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun

# Analytics
# google-analytics:
ga: UA-56205180-3

disqus: haeguri

# Copyright Infomation
startyear: 2018